[package]
name = "ani-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
curl = "0.4.41"
regex = "1.5.4"
open = "2.0.2"